name: helpayr
description: A free Flutter project coded by Jesreal.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.5"

dependencies:
  anim_search_bar: ^2.0.2
  animated_text_kit: ^4.2.2
  bottom_navy_bar: ^6.0.0
  carousel_slider: ^2.2.1
  circle_bottom_navigation_bar: ^1.0.0
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^1.0.3
  email_validator: ^2.1.17
  faker: ^2.0.0
  file_picker: ^5.2.0+1
  firebase_auth: ^3.11.1
  firebase_core: ^1.24.0
  firebase_database: ^9.1.7
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.5
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.8.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hidable: ^1.0.3
  image_picker: ^0.8.6
  lottie: ^1.4.3
  ndialog: ^4.2.0
  page_transition: ^2.0.9
  scroll_snap_list: ^0.9.1
  scrollable_positioned_list: ^0.1.7
  simple_animations: ^5.0.0+2
  smooth_page_indicator: ^1.0.0+2
  stacked_page_view: ^1.1.2
  stream_chat_flutter: ^4.6.0
  syncfusion_flutter_charts: ^20.3.58

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.10
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/helpayr logo2.png"
  android: true
  linux: true
flutter_native_splash:
  image: assets/helpayrblue.png
  color: "#5075C7"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/construction/
    - assets/designing/
    - assets/onboarding new/
    - assets/login/
    - assets/
    - assets/imgs/
    - assets/imgs/onboarding-free.png
    - assets/helpayr logo2.png
    - assets/helpayrblue.png
    - assets/pngs/
    - assets/construction/carpenter.png
    - assets/construction/laborer.png
    - assets/construction/marginalia-electrician-fixing-sockets.png
    - assets/construction/plumber.png
    - assets/construction/welder.png
    - assets/editing/photo
    - assets/editing/photographer
    - assets/editing/producer
    - assets/editing/undraw_video_files_fu10
    - assets/editing/undraw_videographer_re_11sb
    - assets/editing/videoedit
    - assets/food/clip-cake.png
    - assets/food/lime-chef.png
    - assets/food/clip-cake.png
    - assets/other/dance.png
    - assets/other/juicy-business-coach-explains-the-material-to-the-woman.gif
    - assets/other/tailor.png
    - assets/other/clip-974.png

    - assets/repair/automotive.png
    - assets/repair/bike repair.png
    - assets/repair/car_tire.png
    - assets/repair/motorcycle.gif
    - assets/onboarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
