// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSDaRVPDgvQM_V_MoxtpBJ_fJcUXhwLb8',
    appId: '1:924328309699:web:5e5ebb5fcb12d989048376',
    messagingSenderId: '924328309699',
    projectId: 'helpayr-58b50',
    authDomain: 'helpayr-58b50.firebaseapp.com',
    storageBucket: 'helpayr-58b50.appspot.com',
    measurementId: 'G-TPZEGW0EPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWvOOT0E8C8xRM397PVH3ZrMXcHNoZsRo',
    appId: '1:924328309699:android:f325023f7b3859cf048376',
    messagingSenderId: '924328309699',
    projectId: 'helpayr-58b50',
    storageBucket: 'helpayr-58b50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MmEKOa6-5tlqbTAc2RuBFnB8LD7_hNM',
    appId: '1:924328309699:ios:0c704a39275d1e0e048376',
    messagingSenderId: '924328309699',
    projectId: 'helpayr-58b50',
    storageBucket: 'helpayr-58b50.appspot.com',
    iosClientId: '924328309699-u1rbq5omfkvkld1qfhp405hn3tl622vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.day4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4MmEKOa6-5tlqbTAc2RuBFnB8LD7_hNM',
    appId: '1:924328309699:ios:0c704a39275d1e0e048376',
    messagingSenderId: '924328309699',
    projectId: 'helpayr-58b50',
    storageBucket: 'helpayr-58b50.appspot.com',
    iosClientId: '924328309699-u1rbq5omfkvkld1qfhp405hn3tl622vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.day4',
  );
}
